### ISSUE TITLE
Context Breaks

### ISSUE THREAD

**Issue by ways2read** [ways2read/InDesignA11Y#21]
Knowledge base reference: http://kb.daisy.org/publishing/docs/html/context.html

**Comment by LauraB7** [comment]
User story: "As a screen reader user I hear when there is a change in context in the book, so my experience is equitable to someone who sees the visual separator."

**Comment by jonaslil** [comment]
## Background

Context breaks—shifts in thought, time, location, or similar—are often represented by noticeable blank spaces between paragraphs. They may include embellishments like characters (e.g., asterisks) or images.
 
In EPUB, context breaks should be marked with a self-closing `<hr/>` element.

## Current status

InDesign’s current EPUB export does not support creating an empty, self-closing `<hr>` element for context breaks, nor does it include the appropriate CSS styling.
 
For example:

- A paragraph containing asterisks with `hr` assigned as the export tag is exported with the following invalid markup:
`<hr class="asterisks">***</hr>`.
- An empty paragraph export tagged as `hr` is not exported at all.

## Types of context breaks

Context breaks in book layouts are typically represented in three ways: blank space, characters, or images. Below are recommendations for mapping these to EPUB/HTML structures:

**1. Blank Space**
- InDesign: Empty paragraph styled with a paragraph style.
- HTML: `<hr/>` with a class.
- CSS: Use the class to hide the default horizontal line and apply horizontal spacing. 
See Daisy Knowledge Base, [Example 1](http://kb.daisy.org/publishing/docs/html/context.html#ex-01)

**2. Characters (e.g., asterisk)**
- InDesign: Paragraph containing the character(s), styled with a paragraph style.
- HTML: `<hr/>` with a class.
- CSS: Hide the default horizontal line. Use the ::after pseudo-element to add the character(s) and style them as needed.

**3. Images**
- InDesign: Paragraph containing an inline image, styled with a paragraph style.
- HTML: `<hr/>` with a class.
- CSS: Similar to the character-based approach, but use the background property to display the image instead of ::after. 
See Daisy Knowledge Base, [Example 2](http://kb.daisy.org/publishing/docs/html/context.html#ex-02)

## Proposed solution

- When `hr` is assigned as the export tag for a paragraph style, the exported element should be empty and self-closing.
- Add CSS support for styling the `<hr/>` tag to accomodate the various types of context breaks, prioritizing them in the order they are listed above.

**Comment by jonaslil** [comment]
Here's some sample code for case 2, Characters:

**HTML**

```html
<hr class="asterisk"/>
```

**CSS**

```css
hr.asterisk {
    border: none;
    text-align: center;
    margin: 1em auto;
    font-size: 1.25em;
}
hr.asterisk::after {
    content: "∗";
    display: block;
}
```

**Screenshot of result (Thorium)**:

<img src="https://github.com/user-attachments/assets/b9df5940-9840-43f7-b84d-040f362779db" alt="An hr element displayed as a centered asterisk with vertical spacing between two paragraphs." width="75%">

**Comment by VennelaKailasa** [comment]
Hi @LauraB7 , can you please provide us with the list of all different characters that are used as dingbats?
cc: @gregoriopellegrino , @jonaslil , @ways2read

**Comment by LauraB7** [comment]
Hello @VennelaKailasa. There are no specific characters that publishers use for dingbats. Some of the editorial break markers are driven by fonts, not images, and so what is keyed in the paragraph could be anything. It could be asterisks (***) or em-dashes (——) or blank. Or it might be a lower-case e, for example, with a font shift applied so that it's displaying an ornament of some kind. As such, it's best to not to restrict the context break markers.

**Comment by VennelaKailasa** [comment]
Hi @LauraB7, you are absolutely right — dingbats can be of any character, not just those from the Unicode dingbat block. I initially misunderstood dingbats as only special character breaks, but I now see that any keyed-in character used as an ornamental break (like `***`, em-dashes, or even a styled letter) would qualify as a dingbat.

From a **development standpoint**, though, I’m classifying context breaks into these categories for implementation:

1. **Empty Paragraph Breaks** – new lines, blank spaces, or empty paragraphs.
2. **Text Breaks** – paragraphs with text but no inline image. This can include dingbat markers, since they’re effectively text-based.
3. **Image Breaks** – paragraphs that contain inline images.

This way, dingbats are covered under the *text break* category, even if they’re visually styled or decorative.

**Comment by Nainabhandari24** [comment]
Hi @LauraB7 @gregoriopellegrino @ways2read @jonaslil ,

The "Accessibility- Context Break" feature is available in the InDesign Pre-release build 21.0.0.156, with the following known issues:

- Anchored Image and Paragraph with style tagged "hr" disappear in reflowable epub.
- Lines are emitted for blank lines with "hr" tagged paragraph style in vertical text exported to reflowable epub.
- Context break is not applied for all the copied images.
- Duplicates dingbat characters observed when user applied character style and paragraph style having "hr" tag.
- When an anchored image is placed within a paragraph style that includes an "hr" tag, the associated alt text may not be displayed as expected.

We would appreciate it if you could review this and let us know if there are any possible improvements that can be made.

CC: @VennelaKailasa 

Thanks,
Naina

**Comment by VennelaKailasa** [comment]
Hi @LauraB7 @gregoriopellegrino @ways2read @jonaslil,

Could you please help us with the following two issues we are facing:

1. Vertical rule in vertical text frames:
When the "hr" tag is applied, we are seeing a vertical rule appear in vertical text frames.
Adding height: 0 in CSS removes the line, but we need confirmation if this is the correct and valid approach to handle this case.
2. Character style information lost:
Currently, when deleting children in the HTML, the character style information (applied via <span> tags with CSS) is lost.
This results in styled text not being preserved. Could you suggest the recommended way to handle cases where a character style is applied?

We are targeting these fixes for the MAX release, so your quick inputs and guidance on the best solutions would be greatly appreciated.

cc: @Nainabhandari24

**Comment by VennelaKailasa** [comment]
Hi @LauraB7 @gregoriopellegrino @ways2read @jonaslil, just a gentle reminder about the above queries

**Comment by ways2read** [comment]
We met and discussed today.

On the **vertical rule in vertical text frames** issue we want to look at the following CSS as a suitable solution:
hr.asterisk {
    border: none;
    text-align: center;
    margin: 1em auto;
    font-size: 1.25em;
}
hr.asterisk::after {
    content: "∗";
    display: block;
}

On **character style information lost** it would be good to explore migrating the character styling to the CSS for the hr or pseudo element rules.

**Comment by jonaslil** [comment]
Hi @VennelaKailasa,
here's some feedback on you questions and another issue we noticed.

**1. Vertical rule in vertical text frames**

> When the "hr" tag is applied, we are seeing a vertical rule appear in vertical text frames.
Adding height: 0 in CSS removes the line, but we need confirmation if this is the correct and valid approach to handle this case.

We recommend using `border: none` instead of zero width or height values to hide the `<hr>`. In our tests, this works in both vertical and horizontal writing modes.
 
Currently `width: 0` is used to hide the rule for empty context breaks, which leaves a visible dot in some reading apps. Replacing this with `border: none` resolves the issue.

**2. Character style information lost**

> Currently, when deleting children in the HTML, the character style information (applied via tags with CSS) is lost.
This results in styled text not being preserved. Could you suggest the recommended way to handle cases where a character style is applied?

Character styles would only be needed if some characters in a context break are styled differently from others. This is a rare edge case, and trying to preserve it introduces complexity in the CSS output. After reconsidering, we suggest not trying to preserve character style formatting for context breaks.

**Image context breaks**
Images may currently appear cropped, with only part of the image visible. This happens when the background image is larger than the `<hr>` box (`height: 1em`).

Proposed fix: add `background-size: auto 100%;` to the ruleset that sets the background image.

This scales the image to fit the `<hr>` height while keeping its aspect ratio. (`auto` sets the width, `100%` the height).

**Comment by jonaslil** [comment]
@VennelaKailasa,
We've discussed this issue in the expert group and have some new ideas for improving the CSS. We are preparing a test file to demonstrate our approach.

**Comment by VennelaKailasa** [comment]
Sure @jonaslil , but just a heads up, all these new changes will be going in next release i.e., 21.1 and for the above queries,
1. We'll add border as none
2. In 21.0 if any character style is applied it's respective css will be moved / added in context break class
3. background-size will be added 
4. Also please provide suggestions on the below item
4.a In InDesign’s reflowable EPUB export, any empty or new line is removed regardless of the tag applied. However, when an "hr" tag is used, should this line be preserved to maintain a visible context break between paragraphs? Otherwise, sighted readers may not perceive the separation that the "hr" represents.
cc: @Nainabhandari24

**Comment by jonaslil** [comment]
Hello @VennelaKailasa,
We've prepared an EPUB file to illustrate our proposed CSS improvements for context breaks. 
[Context break test file](https://github.com/user-attachments/files/22902794/context_breaks.zip)

#### Question 4 - Blank context breaks

The space of the empty paragraph exported as `<hr>` should be reflected in the CSS to ensure the break remains visible. Empty paragraphs or line breaks in the HTML are not a reliable solution.
 
Proposed fix:

```css
block-size: 1.2em;
```
 
The value in em should match the line-height applied to the `<hr>` element.

Below are some other issues we noted and proposed solutions.

#### Proliferation of classes

Each instance of a character or image context break generates a new class, sometimes resulting in hundreds of repeated declarations.

Proposed fix:

- Use a single auto-generated class for character context breaks with the same text content
- Use a single auto-generated class for image context breaks where the linked image and image size are the same

#### Conflicting rules: paragraph-style CSS vs. default CSS

For character and blank context breaks, default CSS rules override the paragraph-style–based rules.

Proposed fix: 
- Properties already covered by the paragraph style (e.g. margins, text-align) should not be repeated in the auto-generated class ruleset
- Common styles for all context breaks (e.g. `border:none;`) should go in the paragraph-style ruleset
- Styles specific to each type of context break should go in the auto-generated class ruleset

#### Paragraph-style rules ignored for image context breaks

Because the background-image rule is defined in the auto-generated class, paragraph-style rules have no effect.

Proposed fix: 
Define styles specific to image context breaks with a combined class selector, for example: `hr.cb._idImageContextBreak-1`.  
(cb = paragraph-style class)

#### Image size not respected

InDesign exports the height and width of context break images using auto-generated classes, but these classes are not referenced in the HTML.

Proposed fix: 
In the ruleset for image context breaks, set the height according to the image size in the InDesign layout.

**Comment by VennelaKailasa** [comment]
Hi @jonaslil and team, we've started working on this FMR and it'll be released in 21.3 of InDesign. 
cc: @Nainabhandari24

**Comment by raman211** [comment]
Hi @jonaslil 
The rest of the open items (except for **Conflicting rules: paragraph-style CSS vs. default CSS** ) are fixed and already part of the ID21.2.0.15 pre-release build
Please help us by sharing your feedback on those.
CC: @gregoriopellegrino @ways2read @LauraB7 @VennelaKailasa @Nainabhandari24

**Comment by jonaslil** [comment]
The context breaks work much better now, with cleaner CSS that is more faithful to the InDesign layout. We still see issues with classes being multiplied, especially for character context breaks. Below is our detailed feedback based on testing in prerelease 21.2 Build 30 and in the 21.2 release.

#### Blank context breaks

**Fixed.** CSS `block-size` rule is exported for blank context breaks.

#### Proliferation of classes

"Use a single auto-generated class for character context breaks with the same text content"

**Not fixed.** For each character context break, a new class is generated. Example:

````css
hr.charcb._idCharacterContextBreak-1 {
	border:none;
}
hr.charcb._idCharacterContextBreak-1::after {
	content:'***';
	display:block;
}
hr.charcb._idCharacterContextBreak-2 {
	border:none;
}
hr.charcb._idCharacterContextBreak-2::after {
	content:'***';
	display:block;
}
````

"Use a single auto-generated class for image context breaks where the linked image and image size are the same"

**Partially fixed**, but not consistent in all cases.

In one test, two context breaks using the same SVG image with identical frame height and width were not exported with the same class. Files demonstrating the issue: 
[Context breaks sample](https://github.com/user-attachments/files/25016877/context_breaks.zip)

#### Conflicting rules: paragraph-style CSS vs. default CSS

**Fixed.** We no longer see any conflicting rules. The default rules for margins and text alignment, which previously conflicted with paragraph style based rules, have been removed.

#### Image size not respected

**Partially fixed.** The height is exported in CSS rules for image context breaks.

Remaining issues noted:
- The height of the background image is defined in pixels, which means it does scale proportionately with the text in all reading apps.
- For image context breaks using SVG images, the exported pixel size is too large compared to the InDesign layout.

Proposed fixes:
- Use `em` values for background image height.
- Check rules used to calculate CSS height for SVG images.

**Comment by Nainabhandari24** [comment]
Hi @jonaslil ,

We have fixed "Conflicting rules: paragraph-style CSS vs. default CSS" on  21.3.0.34 pre-release build.
Please help us by sharing your feedback on that.

Thanks,
Naina

**Comment by jonaslil** [comment]
Here's our feedback based on testing in prerelease build 21.3.0.49:
 
We can confirm that “Conflicting rules: paragraph-style CSS vs. default CSS" is fixed. The CSS also looks a bit cleaner than last time we tested.
 
The other issues noted in https://github.com/ways2read/InDesignA11Y/issues/21#issuecomment-3835890774 remain.

**Comment by Nainabhandari24** [comment]
Hi @jonaslil ,

We request you to validate feature on ID/IC 21.3.0.58 pre-release build and share your feedback. We have fixed below issues.
- [ID-4275968]: Height of the background image need to be defined in em.
- [ID-4275966]: Multiple classes were generated for same character/image context break.

Thanks,
Naina

**Comment by jonaslil** [comment]
Thank you @Nainabhandari24. Here’s our feedback based on testing in the 21.3.0.58 prerelease build.
 
**[ID-4275968]: Height of the background image needs to be defined in em.**
 
Confirmed: Height is now defined in em.
 
Question:
A PNG with height 36px in InDesign is exported as 2em, suggesting a divisor of 18 instead of the expected 16.
With 16, the result would be 2.25em, which better matches the layout. The image appears smaller in the EPUB. Could you check the calculation?
 
**[ID-4275966]: Multiple classes were generated for same character/image context break.**
 
Confirmed: No duplication for paragraph context breaks.
 
However, issues remain for SVG image context breaks. The output depends on the export settings:
 
1. Preserve appearance from layout checked
- SVG converted to PNG 
- Separate PNG for each instance 
- Classes duplicated 
- Height larger than expected

```css
hr.cb._idImageContextBreak-2 {
    background:url('../image/Aldus_leaf1.png') no-repeat center;
    background-size:auto 100%;
    height:3em;
}
hr.cb._idImageContextBreak-3 {
    background:url('../image/Aldus_leaf2.png') no-repeat center;
    background-size:auto 100%;
   height:3em;
}
```

2. Preserve appearance unchecked + SVG as Embed Code/Object Tags
- No class duplication 
- Converted to character context break with an object replacement character

```css
hr.cb._idCharacterContextBreak-3::after {
    content:'￼';
    display:block;
}
```
 
3. Preserve appearance unchecked + SVG as Image Tags
- Correct structure (image context break with SVG background) 
- Missing height → image not rendered

```css 
hr.cb._idImageContextBreak-2 {
    background:url('../image/Aldus_leaf.svg') no-repeat center;
    background-size:auto 100%;
}
```

**Suggested fixes:**
- With Preserve appearance from layout checked:
  - Avoid duplication of PNG assets and classes. 
  - Check calculation of background image height.
- With Preserve appearance from layout unchecked:
  - Consistently export as an image context break with SVG background, regardless of “Use SVG as”.
  - Ensure height is defined in em.

**Comment by Nainabhandari24** [comment]
Hi @jonaslil ,

Thanks for the feedback. We will work on this.

Thanks,
Naina

**Comment by Nainabhandari24** [comment]
Hi @jonaslil ,
We have addressed all the above-mentioned issues in pre-release build 21.4.0.62.

Regarding the issue you mentioned about multiple CSS classes being generated for the same SVG image with context breaks—this is not actually a bug. When the container styles and the inserted SVG image remain the same, no duplicate images or context break classes are created. However, when the container styles change, even if the inserted SVG is identical, it gets rasterized into a different PNG. As a result, the context break class name also changes.

This behavior—where multiple rasterized images are generated—can also be observed even without applying the context break tag (hr).

CC: @raman211 

Thanks,
Naina
